### ISSUE TITLE
feat: basic exec

### ISSUE THREAD

**Issue by Oktosha** [Oktosha/codam-minishell#17]
Write a basic way to launch non-built-in commands:

+ come up with a data structure passed from the parsing part into exec part
+ do basic launching
+ write a basic testing script (at least for manual testing)

This issue isn't about integrating signals or handling all the weird cases

**Comment by Oktosha** [comment]
Staff to think about (here or for full exec)

+ what should be the priorities for choosing the executable?
  - built-in vs binaries
  - binaries in path
  - binary vs non-binary with the same name in different folders in path
+ which exit code should be saved for `$?` command

**Comment by elenavoronin** [comment]
We finalised this part of minishell. Closed.

**Comment by Oktosha** [comment]
What should the child process know?
Args?
Env vars?
Signal mask?

**Comment by Oktosha** [comment]
**Notes on path lookup**

if the exec “name” contains “/“ (i. e. folder) nobody looks it up in path, you just have to try; otherwise, append this name to every path item

/usr/bin:/usr/local/bin:: <- empty string in Path means current folder

can a folder in PATH contain a colon? nope
can a folder in PATH contain space?

**Comment by Oktosha** [comment]
**Notes on args**

assert(argv[argc] == NULL)

argv[0] is exactly the string you’ve used to launch the program (./a.out, a.out, /Users/daria/a.out)

**Comment by Oktosha** [comment]
**Notes on env vars**

Can env variable name contain equals sign?
Can env variable value contain equals sign? yes

**Comment by Oktosha** [comment]
If a file in PATH can't be executed, it is ignored; bash tries to find the thing in the next folder; however, zsh always says "command not found" if it can't find the executable one and bash sometimes says "permission denied"

**Comment by Oktosha** [comment]
if PATH is unset, it behaves like a PATH containing only empty string, i. e. searches only in the current directory

**Comment by Oktosha** [comment]
What if PATH contains space?
