### ISSUE TITLE
feat: Lifecycle code to glue stuff

### ISSUE THREAD

**Issue by Oktosha** [Oktosha/codam-minishell#22]

**Comment by Oktosha** [comment]
## 1. Tokenize
This tokenize is very dummy, creates only obvious tokens and doesn’t even care about the quotes

## 2. Lex
The goal of lex is to do enough work to prepare for the env vars expansion.

2.1 Mark quotes as important and non-important
2.2 Mark heredoc, pipe, redirect depending on the quotes
2.3 Mark variables ($WORD and $?) taking heredoc and quotes into account

## 3. Expand
Expand variables

## 4. Parse

Finally create commands.

4.1 Un-quote things, also mark if there were quotes inside heredoc delimeters
4.2 Group words together
4.3 Get rid of whitespace
4.4 Group commands

## 5. Heredoc input
Input all the heredocs, don’t forget about proper expansion in heredocs

## 6. Exec
Run commands

## 7. Cleanup 
(free line, free tokens, free commands…)

## think about: signals

What if the minishell process gets signal?
Decision: minishell dies on every signal it receives

How do we handle ctrl-C ctrl-D and ctrl-\? (In command input, in heredoc input and when a child is at work)

**Comment by elenavoronin** [comment]
free kotistate in l_lc_clear_kotistate (lifecycle_a.c)
